// <auto-generated />
namespace PROYECTO_ISO810.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EmpleadosModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpleadosModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202405140508188_EmpleadosModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
